# Ray casts give the center of the first occupied cell. If it matches the target point is checked b the distance between them.
# If distance <= sqrt(3)/2 * node_size + tolerance, the target is marked as visible. (Cube diagonal = sqrt(3)*edge_length)
distance_tolerance: 0.005